-- Media.lua
-- Get a reference to the main addon object
local cbUF = LibStub("AceAddon-3.0"):GetAddon("cbUnitFrames")
if not cbUF then return end

-- Define the path to this addon's media folder
local addonPath = "Interface\\AddOns\\cbUnitFrames\\Media\\BarTextures\\"

-- Register all your built-in textures by adding them to the public table
table.insert(cbUF.media.barTextures, { path = addonPath .. "ToxiUI-clean.tga", name = "ToxiUI Clean (Default)" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "ToxiUI-dark.tga",  name = "ToxiUI Dark" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "bar_tukui.tga",    name = "Tukui Style" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-R.tga",       name = "pfUI Style R" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "Bezo-dark1.blp",   name = "Bezo Dark 1" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "Bezo-dark2.blp",   name = "Bezo Dark 2" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "Bezo.blp",         name = "Bezo" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "BuiOnePixel.tga",  name = "Bui One Pixel" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "GeminiISALIAR.tga",name = "Gemini ISALIAR" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-A.tga",       name = "pfUI Style A" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-B.tga",       name = "pfUI Style B" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-C.tga",       name = "pfUI Style C" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-D.tga",       name = "pfUI Style D" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-E.tga",       name = "pfUI Style E" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-F.tga",       name = "pfUI Style F" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-G.tga",       name = "pfUI Style G" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-H.tga",       name = "pfUI Style H" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-I.tga",       name = "pfUI Style I" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-J.tga",       name = "pfUI Style J" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-K.tga",       name = "pfUI Style K" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-L.tga",       name = "pfUI Style L" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-M.tga",       name = "pfUI Style M" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-N.tga",       name = "pfUI Style N" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-O.tga",       name = "pfUI Style O" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-P.tga",       name = "pfUI Style P" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-Q.tga",       name = "pfUI Style Q" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-S.tga",       name = "pfUI Style S" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-T.tga",       name = "pfUI Style T" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-U.tga",       name = "pfUI Style U" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-V.tga",       name = "pfUI Style V" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-W.tga",       name = "pfUI Style W" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-X.tga",       name = "pfUI Style X" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "pfUI-Y.tga",       name = "pfUI Style Y" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "ToxiUI-fade.blp",  name = "ToxiUI Fade" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "ToxiUI-g1.tga",    name = "ToxiUI G1" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "ToxiUI-g2.tga",    name = "ToxiUI G2" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "ToxiUI-grad.tga",  name = "ToxiUI Grad" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "ToxiUI-half-transparent-stroke.blp", name = "ToxiUI Half Transparent Stroke" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "ToxiUI-half-transparent.blp", name = "ToxiUI Half Transparent" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "ToxiUI-half.tga",  name = "ToxiUI Half" })
table.insert(cbUF.media.barTextures, { path = addonPath .. "TX-WorldState-Score.blp", name = "TX WorldState Score" })